/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BaoGiaIdRouteImport } from './routes/bao-gia.$id'
import { Route as PhieuTntmIndexRouteImport } from './routes/phieu-tntm.index'
import { Route as PhieuTntmIdRouteImport } from './routes/phieu-tntm.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BaoGiaIdRoute = BaoGiaIdRouteImport.update({
  id: '/bao-gia/$id',
  path: '/bao-gia/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PhieuTntmIndexRoute = PhieuTntmIndexRouteImport.update({
  id: '/phieu-tntm/',
  path: '/phieu-tntm/',
  getParentRoute: () => rootRouteImport,
} as any)
const PhieuTntmIdRoute = PhieuTntmIdRouteImport.update({
  id: '/phieu-tntm/$id',
  path: '/phieu-tntm/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bao-gia/$id': typeof BaoGiaIdRoute
  '/phieu-tntm/$id': typeof PhieuTntmIdRoute
  '/phieu-tntm/': typeof PhieuTntmIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bao-gia/$id': typeof BaoGiaIdRoute
  '/phieu-tntm/$id': typeof PhieuTntmIdRoute
  '/phieu-tntm': typeof PhieuTntmIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bao-gia/$id': typeof BaoGiaIdRoute
  '/phieu-tntm/$id': typeof PhieuTntmIdRoute
  '/phieu-tntm/': typeof PhieuTntmIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bao-gia/$id' | '/phieu-tntm/$id' | '/phieu-tntm/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bao-gia/$id' | '/phieu-tntm/$id' | '/phieu-tntm'
  id: '__root__' | '/' | '/bao-gia/$id' | '/phieu-tntm/$id' | '/phieu-tntm/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BaoGiaIdRoute: typeof BaoGiaIdRoute
  PhieuTntmIdRoute: typeof PhieuTntmIdRoute
  PhieuTntmIndexRoute: typeof PhieuTntmIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bao-gia/$id': {
      id: '/bao-gia/$id'
      path: '/bao-gia/$id'
      fullPath: '/bao-gia/$id'
      preLoaderRoute: typeof BaoGiaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phieu-tntm/': {
      id: '/phieu-tntm/'
      path: '/phieu-tntm'
      fullPath: '/phieu-tntm/'
      preLoaderRoute: typeof PhieuTntmIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phieu-tntm/$id': {
      id: '/phieu-tntm/$id'
      path: '/phieu-tntm/$id'
      fullPath: '/phieu-tntm/$id'
      preLoaderRoute: typeof PhieuTntmIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BaoGiaIdRoute: BaoGiaIdRoute,
  PhieuTntmIdRoute: PhieuTntmIdRoute,
  PhieuTntmIndexRoute: PhieuTntmIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
